# Generated by Django 4.2.5 on 2024-02-13 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 13, 7, 29, 44, 234231, tzinfo=datetime.timezone.utc)),
        ),
    ]
